sudo: required

env:
- CHANGE_MINIKUBE_NONE_USER=true K8S_VER=1.9.0 K6T_VER=0.4.1 K6T_VER_PRE=0.3.0 M6E_VER=v0.25.2

notifications:
  irc:
    channels:
      - "chat.freenode.net#kubevirt"
    on_success: change
    on_failure: always

before_script:
# Setup minikube
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v$K8S_VER/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/$M6E_VER/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

- sudo minikube start --vm-driver=none --kubernetes-version=v$K8S_VER
- minikube update-context
- JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done

# Cleanup required for our libvirtd container
# # FIXME needs to be fixed in KubeVirt
- rm -vf /dev/shm ; sudo touch /dev/shm
- rm -vf /dev/mqueue ; sudo mkdir /dev/mqueue

script:
 - bash -n $(ls -1 *.sh)
 - cat demo.sh | bash
